### Exercise 2: Quick Stats & Checking the Table

**Requirements:**
1. Show quickstats summary numbers for all number columns with 1 method.
2. Show a quickstats summary for only the `'Name'` column with 1 method.
3. Print the total count of rows in the table.
4. Print the list of all column names.

<details>
<summary>💡 Need a hint?</summary>

- Full numbers summary: `df.describe()`
- One column summary: `df['Name'].describe()`
- Total rows: `len(df)`
- Column list: `df.columns`
</details>

--------

Import TXT File as Dataframe

In [14]:
import pandas as pd

df = pd.read_csv('./data/pokemon_data.txt' , delimiter='\t')

df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

1. Show quickstats summary numbers for all number columns with 1 method.

In [15]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

2. Show a quickstats summary for only the `'Name'` column with 1 method.

In [16]:
df['Name'].describe()

count                     800
unique                    800
top       PumpkabooSuper Size
freq                        1
Name: Name, dtype: object

3. Print the total count of rows in the table. (How lenghthy is this dataframe)

In [17]:
len(df)

800

4. Print the list of all column names.

In [18]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')