### Exercise 4: Making a New DataFrame from Scratch

**Requirements:**
1. Import `numpy` as `np`.
2. Create a DataFrame with 4 rows and 3 columns using random numbers (can include negative values), and name the columns `'A'`, `'B'`, and `'C'`.
3. Create a DataFrame with 4 rows and 3 columns using a simple Python dictionary.

<details>
<summary>💡 Need a hint?</summary>

- From random array: `pd.DataFrame(data=np.random.randn(4, 3), columns=['A', 'B', 'C'])`
- From dictionary: `pd.DataFrame({'A': [1,2,3,4], 'B': [5,6,7,8], 'C': [9,10,11,12]})`
</details>

-----

Import TXT data file as Dataframe

In [20]:
import pandas as pd

df = pd.read_csv('./data/pokemon_data.txt' , delimiter='\t')

df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

1. Import `numpy` as `np`.
2. Create a DataFrame with 4 rows and 3 columns using random numbers (can include negative values), and name the columns `'A'`, `'B'`, and `'C'`.

In [21]:
import numpy as np

# Should create Dataframe using below method. Hover over it to see parameters
    #df = pd.DataFrame()

data1 = np.random.randint(1,10, (4,3))
columns1 = ['A', 'B', 'C']

#data1

df1 = pd.DataFrame( data=data1 , columns=columns1)

df1

   A  B  C
0  2  2  5
1  7  2  7
2  4  8  6
3  8  7  1

3. Create a DataFrame with 4 rows and 3 columns using a simple Python dictionary.

In [22]:
dict1 = {'A': [0,2,4,1], 'B': [4,1,6,4], 'C': [5,2,6,4]}

df2 = pd.DataFrame(data=dict1)

df2

   A  B  C
0  0  4  5
1  2  1  2
2  4  6  6
3  1  4  4