### Exercise 9: Searching Text, Using Regex, and Changing Values

**Requirements:**
1. Find all Pokémon that have `'Mega'` anywhere inside their name.
2. Using regular expressions (ignore uppercase and lowercase):
   - Find Pokémon where `'Type 1'` is either `'fire'` or `'grass'`.
   - Find Pokémon whose names contain `'pi'` anywhere.
   - Find Pokémon whose names **start** with `'pi'`.
3. Updating table values:
   - In the `'Type 1'` column, change every `'Fire'` to `'FLAME'`.
   - If a Pokémon has `'HP'` greater than 50, set its `'Generation'` to `999` and `'Legendary'` to `True`.

<details>
<summary>💡 Need a hint?</summary>

- Text search: `df.loc[df['Name'].str.contains('Mega')]`
- Regex search: `import re; df.loc[df['Name'].str.contains('^pi', flags=re.I, regex=True)]`
- Change single column: `df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'FLAME'`
- Change multiple columns: `df.loc[df['HP'] > 50, ['Generation', 'Legendary']] = [999, True]`
</details>

----

Import TXT dataset as Dataframe

In [63]:
import pandas as pd

df = pd.read_csv('./data/pokemon_data.txt', delimiter='\t')

df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

1. Find all Pokémon that have `'Mega'` anywhere inside their name.

In [64]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

2. Using regular expressions (ignore uppercase and lowercase):
   - Find Pokémon where `'Type 1'` is either `'fire'` or `'grass'`.

In [65]:
df.loc[df['Type 1'].str.contains('fire|grass', case=False, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

2. Using regular expressions (ignore uppercase and lowercase):
   - Find Pokémon whose names contain `'pi'` anywhere.

In [66]:
df.loc[df['Name'].str.contains('pi', case=False, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
189,175,Togepi,Fairy,NaN,35,20,65,40,65,20,2,False
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
345,316,Gulpin,Poison,NaN,70,43,53,43,53,40,3,False
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,3,False
358,327,Spinda,Normal,NaN,60,60,60,60,60,60,3,False
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,3,False
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,3,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4,False
501,451,Skorupi,Poison,Bug,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,70,90,110,60,75,95,4,False
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False
596,536,Palpitoad,Water,Ground,75,65,55,65,55,69,5,False
716,648,MeloettaPirouette Forme,Normal,Fighting,100,128,90,77,77,128,5,False
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False

2. Using regular expressions (ignore uppercase and lowercase):
   - Find Pokémon whose names **start** with `'pi'`.

In [67]:
df.loc[df['Name'].str.contains('^pi', case=False, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

3. Updating table values:
   - In the `'Type 1'` column, change every `'Fire'` to `'FLAME'`.

In [68]:
df.loc[df['Type 1'].str.contains('fire', case=False, regex=True), ['Type 1']] = 'FLAME'

df.loc[df['Type 1'].str.contains('flame', case=False, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,FLAME,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,FLAME,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,FLAME,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,FLAME,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,FLAME,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,FLAME,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,FLAME,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,FLAME,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,FLAME,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,FLAME,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,FLAME,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,FLAME,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,FLAME,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,FLAME,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,FLAME,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,FLAME,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,FLAME,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,FLAME,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,FLAME,Rock,50,50,120,80,80,30,2,False
259,240,Magby,FLAME,NaN,45,75,37,70,55,83,2,False
263,244,Entei,FLAME,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,FLAME,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,FLAME,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,FLAME,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,FLAME,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,FLAME,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,FLAME,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,FLAME,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,FLAME,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,FLAME,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,FLAME,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,FLAME,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,FLAME,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,FLAME,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,FLAME,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,FLAME,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,FLAME,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,FLAME,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,FLAME,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,FLAME,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,FLAME,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,FLAME,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,FLAME,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,FLAME,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,FLAME,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,FLAME,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,FLAME,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,FLAME,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,FLAME,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,FLAME,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,FLAME,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,FLAME,Water,80,110,120,130,90,70,6,True

3. Updating table values:
   - If a Pokémon has `'HP'` greater than 50, set its `'Generation'` to `999` and `'Legendary'` to `True`.

In [69]:
df.loc[df['HP']>50, ['Generation','Legendary']]

     Generation  Legendary
1             1      False
2             1      False
3             1      False
5             1      False
6             1      False
..          ...        ...
793           6       True
794           6       True
797           6       True
798           6       True
799           6       True

[589 rows x 2 columns]

In [70]:
df.loc[df['HP']>50]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
5,5,Charmeleon,FLAME,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,FLAME,Flying,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,FLAME,Water,80,110,120,130,90,70,6,True